[build]
builder = "nixpacks"

[deploy]
startCommand = "node src/server.js"
healthcheckPath = "/api/health"
healthcheckTimeout = 10
healthcheckInterval = "30s"
restartPolicy = "on-failure"
maxRetries = 5 